# Generated by Django 6.1.1 on 2026-09-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("slug", models.SlugField()),
                ("stock", models.IntegerField()),
                ("active", models.BooleanField()),
            ],
        ),
    ]
