# Generated by Django 6.1.1 on 2026-09-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
